-- Record books for the load test: 150,000 improvements across every book. Throwaway database only.
\set players 20000
\set records 150000
truncate record_scores;
with books(i, game, record_id, lower) as (
  values
    (0, 'asteroids', 'play-days-streak', false),
    (1, 'asteroids', 'threshold-streak', false),
    (2, 'asteroids', 'highest-combo', false),
    (3, 'asteroids', 'wave-time-1', true),
    (4, 'asteroids', 'wave-time-2', true),
    (5, 'asteroids', 'wave-time-3', true),
    (6, 'asteroids', 'wave-time-4', true),
    (7, 'asteroids', 'wave-time-5', true),
    (8, 'asteroids', 'wave-time-6', true),
    (9, 'asteroids', 'wave-time-7', true),
    (10, 'asteroids', 'wave-time-8', true),
    (11, 'asteroids', 'wave-time-9', true),
    (12, 'asteroids', 'wave-time-10', true),
    (13, 'asteroids', 'wave-time-11', true),
    (14, 'asteroids', 'wave-time-12', true),
    (15, 'asteroids', 'wave-time-13', true),
    (16, 'asteroids', 'wave-time-14', true),
    (17, 'asteroids', 'wave-time-15', true),
    (18, 'asteroids', 'wave-time-16', true),
    (19, 'asteroids', 'wave-time-17', true),
    (20, 'asteroids', 'wave-time-18', true),
    (21, 'asteroids', 'wave-time-19', true),
    (22, 'asteroids', 'wave-time-20', true),
    (23, 'patriot', 'play-days-streak', false),
    (24, 'patriot', 'threshold-streak', false),
    (25, 'patriot', 'direct-streak', false),
    (26, 'snake', 'play-days-streak', false),
    (27, 'snake', 'threshold-streak', false),
    (28, 'snake', 'longest', false),
    (29, 'snake', 'fastest-length-20', true),
    (30, 'snake', 'fastest-length-30', true),
    (31, 'snake', 'fastest-length-40', true),
    (32, 'snake', 'fastest-length-50', true),
    (33, 'snake', 'fastest-length-60', true),
    (34, 'snake', 'fastest-length-70', true),
    (35, 'snake', 'fastest-length-80', true),
    (36, 'snake', 'fastest-length-90', true),
    (37, 'snake', 'fastest-length-100', true),
    (38, 'crosswalk', 'play-days-streak', false),
    (39, 'crosswalk', 'threshold-streak', false),
    (40, 'crosswalk', 'most-coins', false),
    (41, 'crosswalk', 'longest-chain', false),
    (42, 'crosswalk', 'near-misses', false),
    (43, 'crosswalk', 'fastest-row-50', true),
    (44, 'crosswalk', 'fastest-row-75', true),
    (45, 'crosswalk', 'fastest-row-100', true),
    (46, 'crosswalk', 'fastest-row-125', true),
    (47, 'crosswalk', 'fastest-row-150', true),
    (48, 'crosswalk', 'fastest-row-175', true),
    (49, 'crosswalk', 'fastest-row-200', true),
    (50, 'stacker', 'play-days-streak', false),
    (51, 'stacker', 'threshold-streak', false),
    (52, 'stacker', 'perfect-streak', false),
    (53, 'centroid', 'play-days-streak', false),
    (54, 'centroid', 'threshold-streak', false),
    (55, 'pop', 'play-days-streak', false),
    (56, 'pop', 'threshold-streak', false),
    (57, 'pop', 'center-streak', false),
    (58, 'simon', 'play-days-streak', false),
    (59, 'simon', 'threshold-streak', false),
    (60, 'spotter', 'play-days-streak', false),
    (61, 'spotter', 'threshold-streak', false),
    (62, 'pellets', 'play-days-streak', false),
    (63, 'pellets', 'threshold-streak', false),
    (64, 'pellets', 'crumb-streak', false),
    (65, 'findbug', 'play-days-streak', false),
    (66, 'findbug', 'threshold-streak', false),
    (67, 'crumbtrail', 'play-days-streak', false),
    (68, 'crumbtrail', 'threshold-streak', false),
    (69, 'crumbtrail', 'most-rows', false),
    (70, 'crumbtrail', 'crumb-streak', false),
    (71, 'crumbtrail', 'chasers-eaten', false),
    (72, 'bop', 'play-days-streak', false),
    (73, 'bop', 'threshold-streak', false),
    (74, 'putt', 'play-days-streak', false),
    (75, 'putt', 'threshold-streak', false),
    (76, 'barrage', 'play-days-streak', false),
    (77, 'barrage', 'threshold-streak', false),
    (78, 'frenzy', 'play-days-streak', false),
    (79, 'frenzy', 'threshold-streak', false),
    (80, 'fireflies', 'play-days-streak', false),
    (81, 'fireflies', 'threshold-streak', false)
),
runs as (
  select n,
    floor(random() * 82)::int as bi,
    'LT' || lpad((floor(power(random(), 1.6) * :players) + 1)::int::text, 5, '0') as name,
    (extract(epoch from now()) * 1000)::bigint - case when random() < 0.4 then (random() * 86400000)::bigint else (random() * 7 * 86400000)::bigint end as at
  from generate_series(1, :records) as n
)
insert into record_scores (id, game, record_id, name, score, at, device)
select md5(runs.n::text || random()::text), books.game, books.record_id, runs.name,
  case when books.lower then (5000 + floor(random() * 120000))::int else (2 + floor(power(random(), 2) * 60))::int end,
  runs.at, case when random() < 0.55 then 'mobile' else 'desktop' end
from runs join books on books.i = runs.bi;
analyze record_scores;
select count(*) as records, count(distinct name) as players, count(distinct game || record_id) as books from record_scores;
