/*
 * Blip's question of the day (poll.ts), planned ahead: day #1 is POLL_FIRST_DAY on the boards' clock, and each
 * day after takes the next question here, round again from the top once the list runs out. A question on
 * /admin can be swapped or edited for its day (poll.ts keeps that in app_meta), which never moves the others.
 * Light and harmless on purpose, for everyone: nothing political, nothing anyone could be hurt by. Two to four
 * answers, each short enough for a narrow card.
 */

export const POLL_FIRST_DAY = '2026-10-09'

export type PlannedPoll = { q: string; options: readonly string[] }

export const POLLS: readonly PlannedPoll[] = [
  { q: 'Best arcade snack?', options: ['Popcorn', 'Nachos', 'Gummy worms', 'Slushie'] },
  { q: 'Cats or dogs?', options: ['Cats', 'Dogs'] },
  { q: 'Your favourite game sound?', options: ['Coin drop', 'Level up', 'Power-up', 'High score'] },
  { q: 'Morning person or night owl?', options: ['Morning', 'Night owl'] },
  { q: 'Pineapple on pizza?', options: ['Yes please', 'No way'] },
  { q: 'Best season of the year?', options: ['Spring', 'Summer', 'Autumn', 'Winter'] },
  { q: 'Pick a superpower', options: ['Flying', 'Invisible', 'Time travel', 'Super speed'] },
  { q: 'How do you eat a cookie?', options: ['In one go', 'Nibbles', 'Dunked', 'Crumbs first'] },
  { q: 'Beach or mountains?', options: ['Beach', 'Mountains'] },
  { q: 'Best ice cream flavour?', options: ['Chocolate', 'Vanilla', 'Strawberry', 'Mint chip'] },
  { q: 'Do you read the instructions?', options: ['Always', 'Only if stuck', 'Never'] },
  { q: 'Best way to play?', options: ['Phone', 'Computer', 'Tablet'] },
  { q: 'Pancakes or waffles?', options: ['Pancakes', 'Waffles'] },
  { q: 'Which would you pet?', options: ['A penguin', 'A sloth', 'A red panda', 'An otter'] },
  { q: 'Your go-to game mood?', options: ['Chill', 'Competitive', 'A bit of both'] },
  { q: 'Rainy day plan?', options: ['Games', 'A movie', 'A nap', 'Baking'] },
  { q: 'Socks with sandals?', options: ['Cosy', 'Crime'] },
  { q: 'Best pizza topping?', options: ['Pepperoni', 'Mushroom', 'Extra cheese', 'Veggies'] },
  { q: 'Space or the deep sea?', options: ['Space', 'Deep sea'] },
  { q: 'Your dream pet?', options: ['A dragon', 'A unicorn', 'A tiny dinosaur', 'A robot dog'] },
  { q: 'Tea or coffee?', options: ['Tea', 'Coffee', 'Neither'] },
  { q: 'Which colour is the best?', options: ['Blue', 'Green', 'Red', 'Purple'] },
  { q: 'How do you start a game?', options: ['Dive right in', 'Read how to play', 'Watch first'] },
  { q: 'Best breakfast?', options: ['Cereal', 'Eggs', 'Toast', 'Skip it'] },
  { q: 'Would you rather be a…', options: ['Wizard', 'Pirate', 'Astronaut', 'Ninja'] },
  { q: 'Sweet or salty snacks?', options: ['Sweet', 'Salty', 'Both at once'] },
  { q: 'Hot chocolate topping?', options: ['Marshmallows', 'Whipped cream', 'Plain'] },
  { q: 'Your sleep style?', options: ['Starfish', 'Curled up', 'On your front', 'All over'] },
  { q: 'Best board game?', options: ['Chess', 'Monopoly', 'Scrabble', 'Uno'] },
  { q: 'Window seat or aisle?', options: ['Window', 'Aisle'] },
  { q: 'Which would you rather have?', options: ['A treehouse', 'A secret room', 'A ball pit'] },
  { q: 'Best fruit?', options: ['Mango', 'Strawberry', 'Banana', 'Watermelon'] },
  { q: 'Spiders: friend or foe?', options: ['Friend', 'Foe', 'Leave me out of it'] },
  { q: 'How loud is your game volume?', options: ['Muted', 'Low', 'Loud'] },
  { q: 'Best kind of weather?', options: ['Sunny', 'Snowy', 'Stormy', 'Foggy'] },
  { q: 'Crunchy or smooth peanut butter?', options: ['Crunchy', 'Smooth'] },
  { q: 'Which would you visit?', options: ['The moon', 'A volcano', 'A rainforest', 'The North Pole'] },
  { q: 'Fries: thin or thick?', options: ['Thin', 'Thick', 'Curly'] },
  { q: 'Best dinosaur?', options: ['T. rex', 'Triceratops', 'Stegosaurus', 'Raptor'] },
  { q: 'Your high-score celebration?', options: ['Fist pump', 'Victory dance', 'Calm nod'] },
  { q: 'Books or films?', options: ['Books', 'Films'] },
  { q: 'Best cookie?', options: ['Chocolate chip', 'Oatmeal', 'Sugar', 'Peanut butter'] },
  { q: 'Pick a theme park ride', options: ['Rollercoaster', 'Ferris wheel', 'Teacups', 'Log flume'] },
  { q: 'How many tabs are open right now?', options: ['1–5', '6–20', 'Too many'] },
  { q: 'Best cereal milk?', options: ['Cold milk', 'Warm milk', 'Dry cereal'] },
  { q: 'Which robot friend?', options: ['Helper bot', 'Pet bot', 'Chef bot', 'Game bot'] },
  { q: 'Do you name your houseplants?', options: ['Of course', 'No', 'No plants'] },
  { q: 'Best sandwich?', options: ['Grilled cheese', 'Club', 'PB and J', 'BLT'] },
  { q: 'Fireworks or northern lights?', options: ['Fireworks', 'Northern lights'] },
  { q: 'Snow day plan?', options: ['Snowman', 'Snowball fight', 'Sledging', 'Stay in'] },
  { q: 'What wins: hat or hood?', options: ['Hat', 'Hood'] },
  { q: 'Best potato?', options: ['Fries', 'Mashed', 'Roast', 'Crisps'] },
  { q: 'Which would you rather ride?', options: ['A dragon', 'A giant turtle', 'A cloud'] },
  { q: 'Pick a hobby to learn', options: ['Guitar', 'Drawing', 'Juggling', 'Cooking'] },
  { q: 'Gum: bubble or mint?', options: ['Bubble', 'Mint'] },
  { q: 'Best time to play games?', options: ['Morning', 'Lunch break', 'Evening', 'Late night'] },
  { q: 'Which is creepier?', options: ['Clowns', 'Dolls', 'Deep water'] },
  { q: 'Best birthday treat?', options: ['Cake', 'Ice cream', 'Cupcakes', 'Pie'] },
  { q: 'Would you live underwater?', options: ['In a heartbeat', 'For a week', 'No thanks'] },
  { q: 'Your favourite shape?', options: ['Circle', 'Star', 'Triangle', 'Heart'] },
  { q: 'Pasta shape?', options: ['Spaghetti', 'Penne', 'Bowties', 'Mac'] },
  { q: 'Talk to animals or speak every language?', options: ['Animals', 'Every language'] },
  { q: 'Best holiday?', options: ['Halloween', 'New Year', 'Birthday', 'Summer break'] },
  { q: 'Cake or pie?', options: ['Cake', 'Pie'] },
  { q: 'How do you like your eggs?', options: ['Scrambled', 'Fried', 'Boiled', 'No eggs'] },
  { q: 'Pick a mythical creature', options: ['Phoenix', 'Mermaid', 'Griffin', 'Yeti'] },
  { q: 'Which is the best smell?', options: ['Rain', 'Fresh bread', 'Cut grass', 'Popcorn'] },
  { q: 'Do you sing in the shower?', options: ['Every time', 'Sometimes', 'Never'] },
  { q: 'Best ocean animal?', options: ['Octopus', 'Dolphin', 'Sea turtle', 'Whale'] },
  { q: 'Your ideal weekend?', options: ['Adventure', 'Relaxing', 'With friends', 'Gaming'] },
  { q: 'Best dipping sauce?', options: ['Ketchup', 'BBQ', 'Ranch', 'Honey mustard'] },
  { q: 'Which would you rather have?', options: ['A jetpack', 'A teleporter', 'A time machine'] },
  { q: 'Left or right handed?', options: ['Left', 'Right', 'Both'] },
  { q: 'Best bug?', options: ['Ladybird', 'Butterfly', 'Firefly', 'Bee'] },
  { q: 'Popcorn: sweet or salty?', options: ['Sweet', 'Salty', 'Butter'] },
  { q: 'How do you eat corn on the cob?', options: ['Typewriter', 'Round and round', 'Cut it off'] },
  { q: 'Which planet would you visit?', options: ['Mars', 'Saturn', 'Jupiter', 'Neptune'] },
  { q: 'Best candy?', options: ['Chocolate', 'Gummies', 'Lollipops', 'Sour candy'] },
  { q: 'Early or right on time?', options: ['Early', 'On time', 'A bit late'] },
  { q: 'Pick a castle feature', options: ['Moat', 'Tower', 'Secret tunnel', 'Dragon'] },
  { q: 'Best kind of music to game to?', options: ['Chiptune', 'Rock', 'Chill beats', 'Silence'] },
  { q: 'Would you go on a sail around the world?', options: ['Yes!', 'Maybe', 'Seasick already'] },
  { q: 'Best pizza crust?', options: ['Thin', 'Deep dish', 'Stuffed'] },
  { q: 'Which is cuter?', options: ['Puppies', 'Kittens', 'Ducklings', 'Bunnies'] },
  { q: 'Your favourite emoji face?', options: ['Laughing', 'Cool', 'Heart eyes', 'Thinking'] },
  { q: 'Best milkshake?', options: ['Chocolate', 'Vanilla', 'Strawberry', 'Cookies'] },
  { q: 'Would you rather explore…', options: ['A jungle', 'A desert', 'A glacier', 'A cave'] },
  { q: 'How do you sort your snacks?', options: ['By colour', 'Best last', 'Best first', 'No order'] },
  { q: 'Best bird?', options: ['Owl', 'Penguin', 'Parrot', 'Hummingbird'] },
  { q: 'Hot or cold weather?', options: ['Hot', 'Cold'] },
  { q: 'Which would you rather be for a day?', options: ['A cat', 'A bird', 'A fish'] },
  { q: 'Soup or salad?', options: ['Soup', 'Salad'] },
  { q: 'Best way to travel?', options: ['Train', 'Plane', 'Road trip', 'Boat'] },
  { q: 'Pick a dessert topping', options: ['Sprinkles', 'Caramel', 'Hot fudge', 'Berries'] },
  { q: 'Do you make your bed?', options: ['Every day', 'Sometimes', 'Why bother'] },
  { q: 'Best kind of puzzle?', options: ['Jigsaw', 'Crossword', 'Sudoku', 'Riddles'] },
  { q: 'Which is the best number?', options: ['3', '7', '8', '42'] },
  { q: 'Would you rather have a…', options: ['Pet dragon', 'Pet robot', 'Pet ghost'] },
  { q: 'Best sound in the world?', options: ['Rain', 'Laughter', 'Ocean waves', 'A cat purring'] },
  { q: 'Toast: light or dark?', options: ['Light', 'Golden', 'Dark'] },
  { q: 'Pick a camping snack', options: ['S’mores', 'Hot dogs', 'Trail mix'] },
  { q: 'Best day of the week?', options: ['Friday', 'Saturday', 'Sunday', 'Monday?!'] },
  { q: 'Would you rather swim with…', options: ['Dolphins', 'Turtles', 'Manta rays'] },
  { q: 'Your favourite arcade cabinet colour?', options: ['Red', 'Blue', 'Black', 'Neon pink'] },
  { q: 'Breakfast for dinner?', options: ['Yes!', 'No'] },
  { q: 'Which would you collect?', options: ['Stamps', 'Coins', 'Stickers', 'Rocks'] },
  { q: 'Best kind of cheese?', options: ['Cheddar', 'Mozzarella', 'Swiss', 'Brie'] },
  { q: 'Do you check the weather?', options: ['Daily', 'Sometimes', 'Never'] },
  { q: 'Which would you rather be good at?', options: ['Dancing', 'Singing', 'Drawing', 'Sports'] },
  { q: 'Best way to cool down?', options: ['Ice lolly', 'Pool', 'Fan', 'Shade'] },
  { q: 'Your bedtime snack?', options: ['Cookie', 'Fruit', 'Milk', 'Nothing'] },
  { q: 'Pick a holiday spot', options: ['Island', 'Big city', 'Countryside', 'Snowy cabin'] },
  { q: 'Would you rather never…', options: ['Get bored', 'Get tired', 'Get hungry'] },
  { q: 'Best thing about Blipka?', options: ['The games', 'The Dailies', 'The prizes', 'Blip!'] },
  { q: 'Which is the best vegetable?', options: ['Carrot', 'Broccoli', 'Corn', 'Peas'] },
  { q: 'Your trick for a tough level?', options: ['Try again', 'Take a break', 'Ask a friend'] },
  { q: 'Best kind of bread?', options: ['White', 'Brown', 'Sourdough', 'Garlic bread'] },
  { q: 'Would you rather have a…', options: ['Slide indoors', 'Rooftop garden', 'Trampoline floor'] },
  { q: 'Best thing to find in a pocket?', options: ['Money', 'A snack', 'A lost toy', 'A note'] },
]
